"""Fixed all models to use consistent Integer IDs

Revision ID: 368f5bcd9339
Revises: 
Create Date: 2025-11-23 12:46:33.030038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368f5bcd9339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('campaign_input', sa.JSON(), nullable=True),
    sa.Column('audience_insights', sa.JSON(), nullable=True),
    sa.Column('campaign_strategy', sa.JSON(), nullable=True),
    sa.Column('exported_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ready', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=True)
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('mime', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('feed_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='created', nullable=True),
    sa.Column('provisional_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_feeds_campaign_id'), 'platform_feeds', ['campaign_id'], unique=False)
    op.create_table('export_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_feed_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_feed_id'], ['platform_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_logs_platform_feed_id'), 'export_logs', ['platform_feed_id'], unique=False)
    op.create_table('facebook_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_feed_id', sa.Integer(), nullable=False),
    sa.Column('ad_account', sa.String(length=128), nullable=True),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('creative', sa.JSON(), nullable=True),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('scheduling', sa.JSON(), nullable=True),
    sa.Column('exported_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_feed_id'], ['platform_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_details_platform_feed_id'), 'facebook_details', ['platform_feed_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facebook_details_platform_feed_id'), table_name='facebook_details')
    op.drop_table('facebook_details')
    op.drop_index(op.f('ix_export_logs_platform_feed_id'), table_name='export_logs')
    op.drop_table('export_logs')
    op.drop_index(op.f('ix_platform_feeds_campaign_id'), table_name='platform_feeds')
    op.drop_table('platform_feeds')
    op.drop_table('uploaded_images')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
