"""Add enhanced status tracking fields

Revision ID: 89d7cbda986d
Revises: 368f5bcd9339
Create Date: 2025-11-23 20:41:57.193307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d7cbda986d'
down_revision: Union[str, Sequence[str], None] = '368f5bcd9339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('meta_status', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('last_export_attempt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('export_history', sa.JSON(), nullable=True))
    op.add_column('platform_feeds', sa.Column('export_status', sa.String(length=50), server_default='pending', nullable=True))
    op.add_column('platform_feeds', sa.Column('export_details', sa.JSON(), nullable=True))
    op.add_column('platform_feeds', sa.Column('exported_ids', sa.JSON(), nullable=True))
    op.add_column('platform_feeds', sa.Column('last_export_attempt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('platform_feeds', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_feeds', 'error_message')
    op.drop_column('platform_feeds', 'last_export_attempt')
    op.drop_column('platform_feeds', 'exported_ids')
    op.drop_column('platform_feeds', 'export_details')
    op.drop_column('platform_feeds', 'export_status')
    op.drop_column('campaigns', 'export_history')
    op.drop_column('campaigns', 'last_export_attempt')
    op.drop_column('campaigns', 'meta_status')
    # ### end Alembic commands ###
